_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/mvtec/faster_rcnn/faster_rcnn_R_101_FPN_all/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 24 #FIXME: update
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('mvtec_trainval_novel_5shot',) #FIXME: change back to "mvtec_trainval_all_5shot"
  TEST: ('mvtec_test_all',) # we actually use "mvtec_novel_samples" for testing
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (3000,)
  MAX_ITER: 8000 #FIXME: change back to 10000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/mvtec/faster_rcnn/faster_rcnn_R_101_FPN_ft_normalized_all_5shot_randnovel"
